[supervisord]
nodaemon=true

[program:chordmini]
directory=/opt/chordmini
command=/opt/venv/bin/gunicorn -w 1 -b 127.0.0.1:5001 --timeout 600 app:app
autostart=true
autorestart=true
priority=10

[program:worker]
directory=/app
command=/opt/venv/bin/python worker.py
autostart=true
autorestart=true
priority=20
